# permissions for end users to edit radarrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: radarr-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: servarr-operator
    app.kubernetes.io/part-of: servarr-operator
    app.kubernetes.io/managed-by: kustomize
  name: radarr-editor-role
rules:
- apiGroups:
  - application.graytonward.com
  resources:
  - radarrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.graytonward.com
  resources:
  - radarrs/status
  verbs:
  - get
