# permissions for end users to edit readarrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: readarr-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pirate-ship
    app.kubernetes.io/part-of: pirate-ship
    app.kubernetes.io/managed-by: kustomize
  name: readarr-editor-role
rules:
- apiGroups:
  - pirateship.graytonward.com.my.domain
  resources:
  - readarrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pirateship.graytonward.com.my.domain
  resources:
  - readarrs/status
  verbs:
  - get
