# permissions for end users to view sonarrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sonarr-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pirate-ship
    app.kubernetes.io/part-of: pirate-ship
    app.kubernetes.io/managed-by: kustomize
  name: sonarr-viewer-role
rules:
- apiGroups:
  - pirateship.graytonward.com.my.domain
  resources:
  - sonarrs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pirateship.graytonward.com.my.domain
  resources:
  - sonarrs/status
  verbs:
  - get
