## Append samples of your project ##
resources:
- pirateship.graytonward.com_v1alpha1_radarr.yaml
- pirateship.graytonward.com_v1alpha1_sonarr.yaml
- pirateship.graytonward.com_v1alpha1_readarr.yaml
- pirateship.graytonward.com_v1alpha1_lidarr.yaml
- pirateship.graytonward.com_v1alpha1_pirateship.yaml
- pirateship.graytonward.com_v1alpha1_prowlarr.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
